---
title: "Zeyuan-510final-milestone1"
author: "Zeyuan Dong"
date: "11/3/2020"
output: html_document
---
```{R}
########set-up

#if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
#BiocManager::install("Glimma")


#if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")


#BiocManager::install("stringr")
library(limma)
library(Glimma)
library(edgeR)
library(Homo.sapiens)
library(stringr)
#library(TCGAbiolinks)
setwd('/Users/dongzeyuan/Desktop/510final')


```


```{r}
#The compressed packages of decompressed files aged 41-50 and decompressed files aged 51-60 were respectively centrally placed in SampleFiles and Samplefiles2 to facilitate subsequent sorting and classification, and finally manually placed into the SAMPLE folder
dir.create("SampleFiles")
filepath <- dir(path ="./gdc_download_20201104_120209.177419",full.names = TRUE)
for(wd in filepath){
  files <-dir(path = wd,pattern="gz$") #View the files that meet the criteria
  fromfilepath <- paste(wd,"/",files,sep ="")
  tofilepath <- paste("./SampleFiles/",files,sep ="")
  file.copy(fromfilepath,tofilepath)
}
setwd('/Users/dongzeyuan/Desktop/510final')
dir.create("SampleFiles2")
filepath <- dir(path ="./gdc_download_20201104_120209.177419 2",full.names = TRUE)
for(wd in filepath){
  files <-dir(path = wd,pattern="gz$") #View the files that meet the criteria
  fromfilepath <- paste(wd,"/",files,sep ="")
  tofilepath <- paste("./SampleFiles2/",files,sep ="")
  file.copy(fromfilepath,tofilepath)
}
#Manually decompress and classify
```

```{r}
#reading in counts data,P1 means the first person, and so on.
setwd('/Users/dongzeyuan/Desktop/510final/SAMPLE')
files <- c("P01.htseq.counts",
"P02.htseq.counts",
"P03.htseq.counts",
"P04.htseq.counts",
"P05.htseq.counts",
"P06.htseq.counts",
"P07.htseq.counts",
"P08.htseq.counts",
"P09.htseq.counts",
"P10.htseq.counts",
"P11.htseq.counts",
"P12.htseq.counts",
"P13.htseq.counts",
"P14.htseq.counts",
"P15.htseq.counts",
"P16.htseq.counts",
"P17.htseq.counts",
"P18.htseq.counts",
"P19.htseq.counts",
"P20.htseq.counts",
"P21.htseq.counts",
"P22.htseq.counts",
"P23.htseq.counts",
"P24.htseq.counts",
"P25.htseq.counts",
"P26.htseq.counts",
"P27.htseq.counts",
"P28.htseq.counts",
"P29.htseq.counts",
"P30.htseq.counts",
"P31.htseq.counts",
"P32.htseq.counts",
"P33.htseq.counts",
"P34.htseq.counts",
"P35.htseq.counts",
"P36.htseq.counts",
"P37.htseq.counts",
"P38.htseq.counts",
"P39.htseq.counts",
"P40.htseq.counts",
"P41.htseq.counts",
"P42.htseq.counts",
"P43.htseq.counts",
"P44.htseq.counts",
"P45.htseq.counts",
"P46.htseq.counts",
"P47.htseq.counts",
"P48.htseq.counts",
"P49.htseq.counts",
"P50.htseq.counts")
#for(i in paste(files, ".gz", sep=""))
#  R.utils::gunzip(i, overwrite=TRUE),

x <- readDGE(files, columns=c(1,2))
```



```{r}
#Take the first three digits of the file name and make it a little bit cleaner
samplenames <-  substring(colnames(x), 1, 3)
samplenames

colnames(x) <- samplenames
```

```{r}
#Age grouping
group <- as.factor(c("41-50","41-50","41-50","41-50","41-50","41-50","41-50","41-50","41-50","41-50","41-50","41-50","41-50","41-50","41-50","41-50","41-50","41-50","41-50","41-50","41-50","41-50","41-50","41-50","41-50","51-60","51-60","51-60","51-60","51-60","51-60","51-60","51-60","51-60","51-60","51-60","51-60","51-60","51-60","51-60","51-60","51-60","51-60","51-60","51-60","51-60","51-60","51-60","51-60","51-60"))
x$samples$group <- group 
```


```{r}
#Find geneid corresponding gene-symbols and locations of chromosome
geneid <- rownames(x)
geneid
#Remove the decimal point at ENSEMBL
gene <- str_match(geneid, "(\\w*).*")
geneid <- gene[,2]
#go through Homo pacakge and get symbol and chromosome location
genes <- select(Homo.sapiens, 
                keys=geneid,
                columns=c('SYMBOL',"TXCHROM"),
                keytype='ENSEMBL')
head(genes)
#Remove duplicate genes
genes <- genes[!duplicated(genes$ENSEMBL),]
#import genes to DGEList
x$genes <- genes
x
```


```{r}
#Preprocessing data
cpm <- cpm(x)
lcpm <- cpm(x, log=TRUE)

```


```{r}
#Take the average and median of Sample Library Size
L <- mean(x$samples$lib.size) * 1e-6
M <- median(x$samples$lib.size) * 1e-6
c(L, M)

```


```{r}
#Just to give you an overview
summary(lcpm)

```

```{r}
#to filter genes, while keeping as many genes as possible with worthwhile counts.
keep.exprs <- filterByExpr(x, group=group)  #really important and automatic function!
x <- x[keep.exprs,, keep.lib.sizes=FALSE]
dim(x)

```


```{r}
#Observe the difference of data before and after filtering
lcpm.cutoff <- log2(10/M + 2/L)
library(RColorBrewer)
nsamples <- ncol(x)
col <- brewer.pal(nsamples, "Paired")
par(mfrow=c(1,2))
plot(density(lcpm[,1]), col=col[1], lwd=2, ylim=c(0,0.26), las=2, main="", xlab="")
title(main="A. Raw data", xlab="Log-cpm")
abline(v=lcpm.cutoff, lty=3)
for (i in 2:nsamples){
den <- density(lcpm[,i])
lines(den$x, den$y, col=col[i], lwd=2)
}
legend("topright", samplenames, text.col=col, bty="n")
lcpm <- cpm(x, log=TRUE)
plot(density(lcpm[,1]), col=col[1], lwd=2, ylim=c(0,0.26), las=2, main="", xlab="")
title(main="B. Filtered data", xlab="Log-cpm")
abline(v=lcpm.cutoff, lty=3)
for (i in 2:nsamples){
den <- density(lcpm[,i])
lines(den$x, den$y, col=col[i], lwd=2)
}
legend("topright", samplenames, text.col=col, bty="n")


```



```{r}
#normalization
x <- calcNormFactors(x, method = "TMM")
x$samples$norm.factors

```


```{r}
#To better demonstrate the normalization, the data were copied and then adjusted so that the count in the first sample was reduced to 5 percent of the original value, while in the second sample they were swelled to five times their original size.
x2 <- x
x2$samples$norm.factors <- 1
x2$counts[,1] <- ceiling(x2$counts[,1]*0.05)
x2$counts[,2] <- x2$counts[,2]*5

```

```{r}
###useless! just showing sth.
par(mfrow=c(1,2))
lcpm <- cpm(x2, log=TRUE)
boxplot(lcpm, las=2, col=col, main="")
title(main="A. Example: Unnormalised data",ylab="Log-cpm")
x2 <- calcNormFactors(x2)  
x2$samples$norm.factors
```


```{r}


lcpm <- cpm(x2, log=TRUE)
boxplot(lcpm, las=2, col=col, main="")
title(main="B. Example: Normalised data",ylab="Log-cpm")
```

```{r}
#Unsupervised clustering of samples
lcpm <- cpm(x, log=TRUE)
par(mfrow=c(1,2))
col.group <- group
levels(col.group) <-  brewer.pal(nlevels(col.group), "Set1")
col.group <- as.character(col.group)
plotMDS(lcpm, labels=group, col=col.group)
title(main="A. Sample groups")
```

```{r}
#The glMDSPlot function generates an HTML page (open in the browser if Launch =TRUE), with the MDS graph displayed in the left pane and the scale of change explained by each dimension shown in the right pane.
glMDSPlot(lcpm, groups=group)
```